import 'package:flutter/material.dart';
import 'package:undawriter_insure/services/api_service.dart';
import 'package:undawriter_insure/screens/signature_screen.dart';

class PaymentScreen extends StatefulWidget {
  final Map<String, dynamic> policyData;
  final double totalPremium;

  const PaymentScreen({
    super.key,
    required this.policyData,
    required this.totalPremium,
  });

  @override
  State<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends State<PaymentScreen> {
  final _formKey = GlobalKey<FormState>();

  String _paymentChannel = 'MOBILE_MONEY';

  // Mobile Money fields
  String _mobileNetwork = 'MTN';
  final _mobileNumberController = TextEditingController();
  final _paymentReferenceController = TextEditingController();

  // Card fields
  final _cardNumberController = TextEditingController();

  bool _isLoading = false;

  void _submitPayment() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final requestData = Map<String, dynamic>.from(widget.policyData);
      requestData['paymentChannel'] = _paymentChannel;
      
      if (_paymentChannel == 'MOBILE_MONEY') {
        requestData['mobileNetwork'] = _mobileNetwork;
        requestData['mobileNumber'] = _mobileNumberController.text;
        requestData['paymentReference'] = _paymentReferenceController.text;
      } else {
        requestData['cardNumber'] = _cardNumberController.text;
        // Mocking the reference for card since it's typically auto-generated by the gateway
        requestData['paymentReference'] = 'CARD-REF-${DateTime.now().millisecondsSinceEpoch}';
      }

      final response = await ApiService.purchaseMotorPolicy(requestData);

      if (!mounted) return;
      
      final policyId = response['policyId']?.toString();
      
      if (policyId != null) {
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (_) => SignatureScreen(policyId: policyId)),
        );
      } else {
        throw Exception('No policy ID returned from server.');
      }
    } catch (e) {
      if (!mounted) return;
      setState(() => _isLoading = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Payment failed: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Payment'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Card(
                color: const Color(0xFFF3F8FB),
                elevation: 0,
                shape: RoundedRectangleBorder(
                  side: const BorderSide(color: Color(0xFF4F98CD), width: 1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(24.0),
                  child: Column(
                    children: [
                      const Text('Total Amount Due', style: TextStyle(color: Color(0xFF061944))),
                      const SizedBox(height: 8),
                      Text(
                        'GHS ${widget.totalPremium.toStringAsFixed(2)}',
                        style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Color(0xFF061944)),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 32),
              const Text('Select Payment Method', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF061944))),
              const SizedBox(height: 16),
              
              DropdownButtonFormField<String>(
                value: _paymentChannel,
                decoration: const InputDecoration(labelText: 'Method', border: OutlineInputBorder()),
                items: const [
                  DropdownMenuItem(value: 'MOBILE_MONEY', child: Text('Mobile Money')),
                  DropdownMenuItem(value: 'CARD', child: Text('Credit/Debit Card')),
                ],
                onChanged: (val) {
                  setState(() {
                    _paymentChannel = val!;
                  });
                },
              ),
              const SizedBox(height: 24),
              
              if (_paymentChannel == 'MOBILE_MONEY') ...[
                DropdownButtonFormField<String>(
                  value: _mobileNetwork,
                  decoration: const InputDecoration(labelText: 'Network', border: OutlineInputBorder()),
                  items: const [
                    DropdownMenuItem(value: 'MTN', child: Text('MTN Mobile Money')),
                    DropdownMenuItem(value: 'VODAFONE', child: Text('Telecel Cash (Vodafone)')),
                    DropdownMenuItem(value: 'AIRTELTIGO', child: Text('AT Money (AirtelTigo)')),
                  ],
                  onChanged: (val) => setState(() => _mobileNetwork = val!),
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _mobileNumberController,
                  decoration: const InputDecoration(labelText: 'Mobile Number', border: OutlineInputBorder()),
                  keyboardType: TextInputType.phone,
                  validator: (v) => v!.isEmpty ? 'Required field' : null,
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _paymentReferenceController,
                  decoration: const InputDecoration(labelText: 'Reference (Optional)', border: OutlineInputBorder()),
                ),
              ] else ...[
                TextFormField(
                  controller: _cardNumberController,
                  decoration: const InputDecoration(labelText: 'Card Number', border: OutlineInputBorder()),
                  keyboardType: TextInputType.number,
                  validator: (v) => v!.isEmpty ? 'Required field' : null,
                ),
                // Expiry and CVV are mocked for now as in the web app typically handled by gateway
                const SizedBox(height: 16),
                Row(
                  children: [
                    Expanded(
                      child: TextFormField(
                        decoration: const InputDecoration(labelText: 'Expiry Date', border: OutlineInputBorder()),
                        keyboardType: TextInputType.datetime,
                        validator: (v) => v!.isEmpty ? 'Required field' : null,
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: TextFormField(
                        decoration: const InputDecoration(labelText: 'CVV', border: OutlineInputBorder()),
                        keyboardType: TextInputType.number,
                        obscureText: true,
                        validator: (v) => v!.isEmpty ? 'Required field' : null,
                      ),
                    ),
                  ],
                ),
              ],
              
              const SizedBox(height: 48),
              ElevatedButton(
                onPressed: _isLoading ? null : _submitPayment,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF061944),
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: _isLoading
                    ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                    : const Text('Pay Now', style: TextStyle(color: Colors.white, fontSize: 16)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
